name: corc_env
channels:
  - defaults
dependencies:
  - python=3.11
  - scipy
  - numpy
  - pyyaml
  - pandas
  - tqdm
  - opentsne
  - seaborn
  - nbconvert
  - ipykernel
  - jupyter
  - jax
  - jaxtyping
  - Cython
  - pip:
    - studenttmixture
    - flarejax
