name: corc_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - scipy
  - pyyaml
  - pandas
  - tqdm
  - opentsne
  - seaborn
  - nbconvert
  - ipykernel
  - anndata
  - configargparse
  - jupyter
  - Cython
  - colorcet
  - scanpy
  - python-igraph
  - openblas
  - dask
  - pip:
    - jax[cuda12]
    - jaxtyping
    - optax
    - studenttmixture
    - flarejax
    - diptest
    - pyslingshot
    - pybind11
    - hnswlib
    - pyVIA
    - densired
    - numpy==1.26.4