name: corc_env
channels:
  - defaults
dependencies:
  - python=3.11
  - scipy
  - numpy
  - pyyaml
  - pandas
  - tqdm
  - opentsne
  - seaborn
  - nbconvert
  - ipykernel
  - jupyter
  - Cython
  - colorcet
  - scanpy
  - python-igraph
  - openblas
  - pip:
    - jax[cuda12]
    - jaxtyping
    - studenttmixture
    - flarejax
    - diptest
