name: tneb
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - scipy<1.13
  - pyyaml
  - pandas
  - tqdm
  - opentsne
  - seaborn
  - nbconvert
  - ipykernel
  - anndata
  - configargparse
  - jupyter
  - Cython
  - colorcet
  - scanpy
  - openblas
  - dask
  - tsnecuda
  - scikit-learn
  - pip:
    - jax[cuda12]
    - jaxtyping
    - optax
    - studenttmixture
    - flarejax
    - diptest
    - pybind11
    - hnswlib
    - python-igraph
    - -e .
