name: densired
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - scipy
  - opentsne
  - tsnecuda
  - ipykernel
  - scikit-learn
  - pytorch
  - matplotlib
  - numpy>=2
  - pip:
    - densired
    - -e .